# Generated by Django 4.2.30 on 2026-09-07 16:36

from django.db import migrations, models
import lobbies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=lobbies.models.generate_room_code, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In progress'), ('ended', 'Ended')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obstacles', models.JSONField(default=list)),
                ('spawn_position', models.JSONField()),
            ],
        ),
    ]
