# Generated by Django 6.1.1 on 2026-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='terrain',
            field=models.JSONField(default=list),
        ),
    ]
